const WHITE = '#fff';
const BLACK = '#000';
const FONT_COLOR = '#fff';
const ACCENT_COLOR = '#f7a35b';
const ACCENT_COLOR2 = '#f75b5b';
const ACCENT_COLOR_DISABLED = '#473d32';
const BACKGROUND_COLOR = '#242223';
const BACKGROUND_COLOR2 = '#282627';
const BACKGROUND_COLOR3 = '#2e2c2d';
const BACKGROUND_COLOR4 = '#383637';
const ADDED_COLOR = '#6ada1a';
const UPDATED_COLOR = '#ffe400';
const DELETED_COLOR = '#f2381b';
const RESTOCK_COLOR = '#c76ae6';

export {
  WHITE,
  BLACK,
  FONT_COLOR,
  ACCENT_COLOR,
  ACCENT_COLOR2,
  ACCENT_COLOR_DISABLED,
  BACKGROUND_COLOR,
  BACKGROUND_COLOR2,
  BACKGROUND_COLOR3,
  BACKGROUND_COLOR4,
  ADDED_COLOR,
  UPDATED_COLOR,
  DELETED_COLOR,
  RESTOCK_COLOR,
};
