const WHITE = '#fff';
const ADDED_COLOR = '#6ada1a';
const UPDATED_COLOR = '#ffe400';
const DELETED_COLOR = '#f2381b';
const RESTOCK_COLOR = '#c76ae6';

export {WHITE, ADDED_COLOR, UPDATED_COLOR, DELETED_COLOR, RESTOCK_COLOR};
