const BAD_REQUEST = 400;
const UNAUTHORIZED = 401;
const INVALID_AUTHORIZATION = 403;
const NOT_FOUND = 404;

const ASSESSMENT_BAD_REQUEST = 470;

export {
  BAD_REQUEST,
  UNAUTHORIZED,
  ASSESSMENT_BAD_REQUEST,
  INVALID_AUTHORIZATION,
  NOT_FOUND,
};
